### PR TITLE
Fix syntax error in self-approve-tidying.yml

### PR DESCRIPTION
**Pull request by matthew-puku**
Bug introduced in ee4d336. When I reordered the object I forgot to adjust the commas.

I should avoid coding without IDE assistance 😄

### CODE REVIEW

**Review by phyzical — APPROVED** [review]

**Review by waldofouche — APPROVED** [review]
Actions are quite hard to get going 😅

**Comment by phyzical** [comment]
could add a test suite that runs the commands i suppose

**Comment by waldofouche** [comment]
ah interesting idea 🤔

**Comment by phyzical** [comment]
https://github.com/actions/upload-artifact/blob/main/.github/workflows/test.yml

as an example

**Pull request merged**
